name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: shalzz/zola-deploy-action@v0.14.1
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
